# 6CS012 Worksheet-0 Solutions
### Python & NumPy for Deep Learning

---
## Section 4: Python Exercises

### Task 1 — Unit Converter

In [1]:
def convert_length(value, direction):
    """
    Converts between meters and feet.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): '1' for meters->feet, '2' for feet->meters.

    Returns:
        float: The converted value.
    """
    if direction == '1':
        result = value * 3.28084
        print(f"{value} m = {result:.4f} ft")
    else:
        result = value / 3.28084
        print(f"{value} ft = {result:.4f} m")
    return result


def convert_weight(value, direction):
    """
    Converts between kilograms and pounds.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): '1' for kg->lbs, '2' for lbs->kg.

    Returns:
        float: The converted value.
    """
    if direction == '1':
        result = value * 2.20462
        print(f"{value} kg = {result:.4f} lbs")
    else:
        result = value / 2.20462
        print(f"{value} lbs = {result:.4f} kg")
    return result


def convert_volume(value, direction):
    """
    Converts between liters and gallons.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): '1' for liters->gallons, '2' for gallons->liters.

    Returns:
        float: The converted value.
    """
    if direction == '1':
        result = value * 0.264172
        print(f"{value} L = {result:.4f} gal")
    else:
        result = value / 0.264172
        print(f"{value} gal = {result:.4f} L")
    return result


def unit_converter():
    """
    Main function: prompts the user to select a conversion type and value,
    performs the conversion, and handles invalid input.

    Returns:
        float or None: The converted value, or None on invalid input.
    """
    print("Choose conversion type:")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (liters <-> gallons)")

    category = input("Enter 1, 2, or 3: ").strip()

    if category not in ('1', '2', '3'):
        print("Invalid category. Please enter 1, 2, or 3.")
        return None

    if category == '1':
        print("  1. Meters -> Feet")
        print("  2. Feet -> Meters")
    elif category == '2':
        print("  1. Kilograms -> Pounds")
        print("  2. Pounds -> Kilograms")
    else:
        print("  1. Liters -> Gallons")
        print("  2. Gallons -> Liters")

    direction = input("Enter 1 or 2: ").strip()
    if direction not in ('1', '2'):
        print("Invalid direction. Please enter 1 or 2.")
        return None

    try:
        value = float(input("Enter the value to convert: "))
    except ValueError:
        print("Invalid input. Please enter a numeric value.")
        return None

    if category == '1':
        return convert_length(value, direction)
    elif category == '2':
        return convert_weight(value, direction)
    else:
        return convert_volume(value, direction)


unit_converter()

Choose conversion type:
1. Length (meters <-> feet)
2. Weight (kg <-> lbs)
3. Volume (liters <-> gallons)
Enter 1, 2, or 3: 5
Invalid category. Please enter 1, 2, or 3.


### Task 2 — Mathematical Operations on a List

In [2]:
def compute_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The sum of all elements.
    """
    return sum(numbers)


def compute_average(numbers):
    """
    Returns the average of a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The average value.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot compute average of an empty list.")
    return sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Returns the maximum value in a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The maximum element.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find maximum of an empty list.")
    return max(numbers)


def compute_minimum(numbers):
    """
    Returns the minimum value in a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The minimum element.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find minimum of an empty list.")
    return min(numbers)


def math_operations():
    """
    Prompts the user to choose a math operation and provide a list of numbers,
    then performs and displays the result. Handles invalid input gracefully.

    Returns:
        float or None: The computed result, or None on invalid input.
    """
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter 1, 2, 3, or 4: ").strip()
    if choice not in ('1', '2', '3', '4'):
        print("Invalid choice.")
        return None

    raw = input("Enter numbers separated by spaces: ").strip()

    try:
        numbers = [float(x) for x in raw.split()]
    except ValueError:
        print("Invalid input. Please enter numeric values only.")
        return None

    try:
        if choice == '1':
            result = compute_sum(numbers)
            print(f"Sum: {result}")
        elif choice == '2':
            result = compute_average(numbers)
            print(f"Average: {result}")
        elif choice == '3':
            result = compute_maximum(numbers)
            print(f"Maximum: {result}")
        else:
            result = compute_minimum(numbers)
            print(f"Minimum: {result}")
        return result
    except ValueError as e:
        print(f"Error: {e}")
        return None


math_operations()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 4
Enter numbers separated by spaces: 5
Minimum: 5.0


5.0

---
## Section 4.2: List Manipulation

In [3]:
# 1. Extract every other element
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))  # [1, 3, 5]


# 2. Slice a sublist (inclusive end)
def get_sublist(lst, start, end):
    return lst[start:end + 1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))    # [3, 4, 5]


# 3. Reverse a list using slicing
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))             # [5, 4, 3, 2, 1]


# 4. Remove first and last elements
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))        # [2, 3, 4]


# 5. Get first n elements
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))          # [1, 2, 3]


# 6. Extract last n elements
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))           # [4, 5]


# 7. Extract elements in reverse order, starting from second-to-last, skipping one
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))         # [5, 3, 1]

[1, 3, 5]
[3, 4, 5]
[5, 4, 3, 2, 1]
[2, 3, 4]
[1, 2, 3]
[4, 5]
[5, 3, 1]


---
## Section 4.3: Nested List Operations

In [4]:
# 1. Flatten a nested list (one level deep)
def flatten(lst):
    return [item for sublist in lst for item in sublist]

print(flatten([[1, 2], [3, 4], [5]]))            # [1, 2, 3, 4, 5]


# 2. Access a nested element by indices
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

print(access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1, 2]))  # 6


# 3. Sum all elements in a nested list (any depth)
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))      # 21


# 4. Remove all occurrences of a specific element from a nested list
def remove_element(lst, elem):
    return [item for item in
            ([remove_element(x, elem) if isinstance(x, list) else x for x in lst])
            if item != elem]

print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # [[1], [3], [4, 5]]


# 5. Find maximum element in a nested list (any depth)
def find_max(lst):
    flat = []
    for item in lst:
        if isinstance(item, list):
            flat.append(find_max(item))
        else:
            flat.append(item)
    return max(flat)

print(find_max([[1, 2], [3, [4, 5]], 6]))        # 6


# 6. Count occurrences of an element in a nested list
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # 3


# 7. Deep flatten (any depth)
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # [1,2,3,4,5,6,7,8]


# 8. Average of all elements in a nested list
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print(average_nested([[1, 2], [3, 4], [5, 6]]))  # 3.5

[1, 2, 3, 4, 5]
6
21
[[1], [3], [4, 5]]
6
3
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


---
## Section 10.1: NumPy — Basic Vector & Matrix Operations

### Problem 1 — Array Creation

In [5]:
import numpy as np

# 1. Empty array 2x2
empty_arr = np.empty((2, 2))
print("1. Empty 2x2:\n", empty_arr)

# 2. All-ones array 4x2
ones_arr = np.ones((4, 2))
print("\n2. Ones 4x2:\n", ones_arr)

# 3. Array filled with a fill value
filled_arr = np.full((3, 3), 7)
print("\n3. Filled with 7 (3x3):\n", filled_arr)

# 4. Zeros with same shape as an existing array
existing = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(existing)
print("\n4. zeros_like existing:\n", zeros_like_arr)

# 5. Ones with same shape as an existing array
ones_like_arr = np.ones_like(existing)
print("\n5. ones_like existing:\n", ones_like_arr)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("\n6. List -> NumPy array:", np_array)

1. Empty 2x2:
 [[3.06080759e-315 0.00000000e+000]
 [9.88131292e-324             nan]]

2. Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. zeros_like existing:
 [[0 0 0]
 [0 0 0]]

5. ones_like existing:
 [[1 1 1]
 [1 1 1]]

6. List -> NumPy array: [1 2 3 4]


### Problem 2 — Numerical Ranges & Array Indexing

In [6]:
import numpy as np

# 1. Values 10 to 49
arr1 = np.arange(10, 50)
print("1. arange 10-49:\n", arr1)

# 2. 3x3 matrix with values 0-8
arr2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0-8):\n", arr2)

# 3. 3x3 identity matrix
arr3 = np.eye(3)
print("\n3. 3x3 identity matrix:\n", arr3)

# 4. Random array of size 30, find mean
arr4 = np.random.random(30)
print("\n4. Mean of random array (size 30):", arr4.mean())

# 5. 10x10 random array, find min and max
arr5 = np.random.random((10, 10))
print("\n5. Min:", arr5.min(), "  Max:", arr5.max())

# 6. Zero array of size 10, replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("\n6. Zero array with 5th element = 1:\n", arr6)

# 7. Reverse array
arr7 = np.array([1, 2, 0, 0, 4, 0])
print("\n7. Reversed array:", arr7[::-1])

# 8. 2D array with 1 on border and 0 inside
arr8 = np.ones((6, 6))
arr8[1:-1, 1:-1] = 0
print("\n8. Border-ones array:\n", arr8)

# 9. 8x8 checkerboard pattern
arr9 = np.zeros((8, 8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9. Checkerboard 8x8:\n", arr9)

1. arange 10-49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0-8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random array (size 30): 0.5504660466842305

5. Min: 0.003338896302008787   Max: 0.9933791378358489

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Border-ones array:
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]

9. Checkerboard 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem 3 — Array Operations

In [7]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add
print("1. x + y:\n", x + y)

# 2. Subtract
print("\n2. x - y:\n", x - y)

# 3. Multiply by scalar
print("\n3. x * 3:\n", x * 3)

# 4. Square each element
print("\n4. x squared:\n", np.square(x))

# 5. Dot products
print("\n5a. v . w (dot product):", np.dot(v, w))
print("5b. x . v:\n", np.dot(x, v))
print("5c. x . y:\n", np.dot(x, y))

# 6. Concatenate
print("\n6a. x and y along rows (axis=0):\n", np.vstack((x, y)))
print("6b. v and w along column (axis=0):\n", np.concatenate((v, w)))

# 7. Concatenate x and v — will raise an error
print("\n7. Attempting np.concatenate(x, v):")
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print(f"   Error: {e}")
    print("   Reason: x has shape", x.shape, "and v has shape", v.shape,
          "— they have different numbers of dimensions, so concatenation along")
    print("   axis=0 fails because x has 2 columns per row but v is 1D.")

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x squared:
 [[ 1  4]
 [ 9 25]]

5a. v . w (dot product): 219
5b. x . v:
 [29 77]
5c. x . y:
 [[19 22]
 [50 58]]

6a. x and y along rows (axis=0):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. v and w along column (axis=0):
 [ 9 10 11 12]

7. Attempting np.concatenate(x, v):
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Reason: x has shape (2, 2) and v has shape (2,) — they have different numbers of dimensions, so concatenation along
   axis=0 fails because x has 2 columns per row but v is 1D.


### Problem 4 — Matrix Operations & Linear Equations

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]], dtype=float)
B = np.array([[5, 3], [2, 1]], dtype=float)

# 1. Prove A . A_inv = I
A_inv = np.linalg.inv(A)
I_check = np.dot(A, A_inv)
print("1. A . A_inv (should be identity):\n", np.round(I_check, 6))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB == BA?", np.allclose(AB, BA))

# 3. Prove (AB)^T = B^T . A^T
lhs = np.dot(A, B).T
rhs = np.dot(B.T, A.T)
print("\n3. (AB)^T:\n", lhs)
print("   B^T . A^T:\n", rhs)
print("   Equal?", np.allclose(lhs, rhs))

# --- Solve the system of linear equations ---
# 2x - 3y + z  = -1
#  x -  y + 2z = -3
# 3x +  y -  z =  9

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]], dtype=float)
B_sys = np.array([-1, -3, 9], dtype=float)

# Using inverse method: X = A_inv . B
A_sys_inv = np.linalg.inv(A_sys)
X_inv = np.dot(A_sys_inv, B_sys)
print("\nSolving 2x-3y+z=-1 | x-y+2z=-3 | 3x+y-z=9")
print("Inverse method -> x={:.4f}, y={:.4f}, z={:.4f}".format(*X_inv))

# Using np.linalg.solve
X_solve = np.linalg.solve(A_sys, B_sys)
print("np.linalg.solve -> x={:.4f}, y={:.4f}, z={:.4f}".format(*X_solve))

---
## Section 10.2: Experiment — How Fast is NumPy?

In [ ]:
import numpy as np
import time

SIZE = 1_000_000

py_a = list(range(SIZE))
py_b = list(range(SIZE))
np_a = np.arange(SIZE, dtype=float)
np_b = np.arange(SIZE, dtype=float)

# ── 1. Element-wise Addition ──────────────────────────────────────────────────
start = time.time()
result_py = [py_a[i] + py_b[i] for i in range(SIZE)]
py_add_time = time.time() - start

start = time.time()
result_np = np_a + np_b
np_add_time = time.time() - start

print("=== Element-wise Addition ===")
print(f"  Python list : {py_add_time:.5f} s")
print(f"  NumPy array : {np_add_time:.5f} s")
print(f"  Speedup     : {py_add_time / np_add_time:.1f}x\n")

# ── 2. Element-wise Multiplication ───────────────────────────────────────────
start = time.time()
result_py = [py_a[i] * py_b[i] for i in range(SIZE)]
py_mul_time = time.time() - start

start = time.time()
result_np = np_a * np_b
np_mul_time = time.time() - start

print("=== Element-wise Multiplication ===")
print(f"  Python list : {py_mul_time:.5f} s")
print(f"  NumPy array : {np_mul_time:.5f} s")
print(f"  Speedup     : {py_mul_time / np_mul_time:.1f}x\n")

# ── 3. Dot Product ────────────────────────────────────────────────────────────
start = time.time()
dot_py = sum(py_a[i] * py_b[i] for i in range(SIZE))
py_dot_time = time.time() - start

start = time.time()
dot_np = np.dot(np_a, np_b)
np_dot_time = time.time() - start

print("=== Dot Product ===")
print(f"  Python list : {py_dot_time:.5f} s")
print(f"  NumPy array : {np_dot_time:.5f} s")
print(f"  Speedup     : {py_dot_time / np_dot_time:.1f}x\n")

# ── 4. Matrix Multiplication (1000x1000) ──────────────────────────────────────
MAT = 1000
py_m1 = [[float(i * MAT + j) for j in range(MAT)] for i in range(MAT)]
py_m2 = [[float(i * MAT + j) for j in range(MAT)] for i in range(MAT)]
np_m1 = np.array(py_m1)
np_m2 = np.array(py_m2)

start = time.time()
result_py_mat = [[sum(py_m1[i][k] * py_m2[k][j] for k in range(MAT))
                  for j in range(MAT)] for i in range(MAT)]
py_mat_time = time.time() - start

start = time.time()
result_np_mat = np.dot(np_m1, np_m2)
np_mat_time = time.time() - start

print("=== Matrix Multiplication (1000x1000) ===")
print(f"  Python list : {py_mat_time:.5f} s")
print(f"  NumPy array : {np_mat_time:.5f} s")
print(f"  Speedup     : {py_mat_time / np_mat_time:.1f}x")

=== Element-wise Addition ===
  Python list : 0.14084 s
  NumPy array : 0.00859 s
  Speedup     : 16.4x

=== Element-wise Multiplication ===
  Python list : 0.12906 s
  NumPy array : 0.00428 s
  Speedup     : 30.2x

=== Dot Product ===
  Python list : 0.09991 s
  NumPy array : 0.00151 s
  Speedup     : 66.1x

